#!/bin/bash
# Dolphin Emulator wrapper script for Flatpak
# Sets up Discord IPC sockets and launches Dolphin

for i in {0..9}; do
  test -S $XDG_RUNTIME_DIR/discord-ipc-$i ||
    ln -sf {app/com.discordapp.Discord,$XDG_RUNTIME_DIR}/discord-ipc-$i;
done
dolphin-emu "$@"
